version: '3.0'

services:
#  db:
#    image: postgres
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - rasa
#     - action_server

  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
      - --endpoints
      - endpoints.yml

  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    command:
      - start
      - --actions
      - actions